### PR TITLE
generate JSON to make it browser-compatible

### LINKED ISSUE #14: make this lib work in browsers & react-native
`fs` is unavailable in these contexts.

Possible solution: On `prepublishOnly`, generate a JSON variant instead of ndjson and publish it as well.

In addition, we would need a `browser`/`react-native` field in `package.json` that points to the browser-/react-native-specific code.

### PR DESCRIPTION
**Pull request by derhuerst**
Closes #14.

### CODE REVIEW

**Comment by juliuste** [comment]
Because `vbb-change-positions-cli` currently appends to `ndjson` files.

**Comment by derhuerst** [comment]
I don't understand. It's fine to alter `data.ndjson` any time. On every `publish`, `data.json` will be regenerated from it.

**Comment by juliuste** [comment]
LGTM, but can you add documentation to the readme?

**Comment by juliuste** [comment]
Published `1.2.0` on npm.

**Pull request merged**
