### PR TITLE
add Hermannstraße

### PR DESCRIPTION
**Pull request by sebkur**
Add data for changing from S41/S42 to U8 and vice versa at Hermannstraße

### CODE REVIEW

**Comment by sebkur** [comment]
Please check if I understood the data model correctly

**Comment by juliuste** [comment]
I'll have a look at it after the #dbhackathon this weekend 😄

**Comment by juliuste** [comment]
LGTM so far, could you also add `S45`, `S46` and `S47` though? 🙃

**Comment by sebkur** [comment]
Sure, I'll see into it

**Pull request merged**
